# Generated by Django 3.1.10 on 2021-05-08 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encryptfinance.users.models
import encryptfinance.utils.validators
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='accept_cookies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Middle Name of User'),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.CreateModel(
            name='UserVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id_type', models.CharField(blank=True, choices=[('PASSPORT', 'PASSPORT'), ('ID_CARD', 'ID CARD'), ('DRIVERS_LICENSE', 'DRIVERS LICENSE')], default='PASSPORT', max_length=15, null=True)),
                ('id_front', models.FileField(help_text='Must be SVG, PNG or JPG files', null=True, upload_to=encryptfinance.users.models.idcard_image, validators=[encryptfinance.utils.validators.validate_uploaded_image_extension], verbose_name='ID Card Front')),
                ('id_back', models.FileField(help_text='Must be SVG, PNG or JPG files', null=True, upload_to=encryptfinance.users.models.idcard_image, validators=[encryptfinance.utils.validators.validate_uploaded_image_extension], verbose_name='ID Card Back')),
                ('bank_statement', models.FileField(blank=True, help_text='Must be PDF or JPG files', null=True, upload_to=encryptfinance.users.models.bank_statement, validators=[encryptfinance.utils.validators.validate_uploaded_pdf_extension], verbose_name='Last 4 Months Bank Statement')),
                ('ssn', models.CharField(blank=True, help_text='Must be valid Social Security Number. *** US Citizens Only', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')], verbose_name='US SSN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verify',
                'verbose_name_plural': 'User Verifies',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('passport', models.FileField(null=True, upload_to=encryptfinance.users.models.profile_image, validators=[encryptfinance.utils.validators.validate_uploaded_image_extension], verbose_name='User Profile Passport')),
                ('bank', models.CharField(blank=True, choices=[('', 'Select Bank'), ('Arvest Bank', 'Arvest Bank'), ('Ally Financial', 'Ally Financial'), ('American Express', 'American Express'), ('Amarillos National Bank', 'Amarillos National Bank'), ('Apple bank for Savings', 'Apple bank for Savings'), ('Bank of Hawaii', 'Bank of Hawaii'), ('Bank of Hope', 'Bank of Hope'), ('Bank United', 'Bank United'), ('BOA', 'Bank of America'), ('Bank United', 'Bank United'), ('Brown Brothers Harriman & Co', 'Brown Brothers Harriman & Co'), ('Barclays', 'Barclays'), ('BMO Harris Bank', 'BMO Harris Bank'), ('Bank OZK', 'Bank OZK'), ('BBVA Compass', 'BBVA Compass'), ('BNP Paribas', 'BNP Paribas'), ('BOK Financial Corporation', 'BOK Financial Corporation'), ('Cathay Bank', 'Cathay Bank'), ('Chartway Federal Credit Union', 'Chartway Federal Credit Union'), ('Capital One', 'Capital One'), ('Capital City Bank', 'Capital City Bank'), ('Chase Bank', 'Chase Bank'), ('Charles Schwab Corporation', 'Charles Schwab Corporation'), ('CG', 'CitiGroup'), ('Credit Suisse', 'Credit Suisse'), ('Comerica', 'Comerica'), ('CIT Group', 'CIT Group'), ('CapitalCity Bank', 'CapitalCity Bank'), ('Credit Union Page', 'Credit Union Page'), ('Citizens Federal Bank', 'Citizens Federal Bank'), ('Chemical Financial Corporation', 'Chemical Financial Corporation'), ('Discover Financial', 'Discover Finacial'), ('Deutsche Bank', 'Deutsche Bank'), ('Douglas County Bank & Trust', 'Douglas County Bank & Trust '), ('Dime Savings Bank of Williamsburgh', 'Dime Savings Bank of Williamsburgh'), ('East West Bank', 'East West Bank'), ('Flagster Bank', 'Flagster Bank'), ('First National of Nebraska', 'First National of Nebraska'), ('FirstBank Holding Co', 'FirstBank Holding Co'), ('First Capital Bank', 'First Capital Bank'), ('First Commercial Bank', 'First Commercial Bank'), ('First Federal Savings Bank of Indiana', 'First Federal Savings Bank of Indiana'), ('First Guaranty Bank of Florida', 'First Guaranty Bank of Florida'), ('First Line Direct', 'First Line Direct'), ('First USA Bank', 'First USA Bank'), ('Fifth Third Bank', 'Fifth Third Bank'), ('First Citizens BancShares', 'First Citizens BancShares'), ('Fulton Financial Corporation', 'Fulton Financial Corporation'), ('First Hawaiian Bank', 'First Hawaiian Bank'), ('First Horizon National Corporation', 'First Horizon National Corporation'), ('Frost Bank', 'Frost Bank'), ('First Midwest Bank', 'First Midwest Bank'), ('Goldman Sachs', 'Goldman Sachs'), ('Grandeur Financials', 'Grandeur Financials'), ('HSBC Bank USA', 'HSBC Bank USA'), ('Home BancShares Conway', 'Home BancShares Conway'), ('Huntington Bancshares', 'Huntington Bancshares'), ('Investors Bank', 'Investors Bank'), ('Íntercity State Bank', 'Íntercity State Bank'), ('KeyCorp', 'KeyCorp'), ('MB Financial', 'MB Financial'), ('Mizuho Financial Group', 'Mizuho Financial Group'), ('Midfirst Bank', 'Midfirst Bank'), ('M&T Bank', 'M&T Bank'), ('MUFG Union Bank ', 'MUFG Union Bank'), ('Morgan Stanley', 'Morgan Stanley'), ('Northern Trust', 'Northern Trust'), ('New  York Community Bank', 'New York Community Bank'), ('Old National Bank', 'Old National Bank'), ('Pacwest Bancorp', 'Pacwest Bancorp'), ('Pinnacle Financial Partners', 'Pinnacle Financial Partners'), ('PNC Financial Services', 'PNC Financial Services'), ('Raymond James Financial', 'Raymond James Financial'), ('RBC Bank', 'RBC Bank'), ('Region Financial Corporation', 'Region Financial Corporation'), ('Satander Bank', 'Satander Bank'), ('Synovus Columbus', 'Synovus Columbus'), ('Synchrony Financial', 'Synchrony Financial'), ('Sterling Bancorp', 'Sterling Bancorp'), ('Simmons Bank', 'Simmons Bank'), ('South State Bank', 'South State Bank'), ('Stifel St. Louise', 'Stifel St. Louise'), ('Suntrust Bank', 'Suntrust Bank'), ('TCF Financial Corporation', 'TCF Financial Corporation'), ('TD Bank', 'TD Bank'), ('The Bank of New York Mellon', 'The Bank of New York Mellon'), ('Texas Capital Bank', 'Texas Capital Bank'), ('UMB Financial Corporation', 'UMB Financial Corporation'), ('Utrecht-America', 'Utrecht-America'), ('United Bank', 'United Bank'), ('USAA', 'USAA'), ('U.S Bank', 'U.S Bank'), ('UBS', 'UBS'), ('Valley National Bank', 'Valley National Bank'), ('Washington Federal', 'Washington Federal'), ('Western Alliance Banorporation', 'Western Alliance Bancorporation'), ('Wintrust Financial', 'Wintrust Finacial'), ('Webster Bank', 'Webster Bank'), ('Wells Fargo', 'Wells Fargo'), ('Zions Bancorporation', 'Zions Bancorporation'), ('Other Bank', 'Other Bank')], max_length=250, null=True, verbose_name='Your Bank Name')),
                ('account_no', models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')], verbose_name='Recipient Account Number')),
                ('routing_no', models.CharField(blank=True, help_text='must be the recipients 9 digits routing number', max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')], verbose_name='Recipient Routing Number')),
                ('phone', models.CharField(blank=True, help_text='Example: 1234567890 (10 digits only)', max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='Invalid_input, Only Integers', message='Must Contain Numbers Only', regex='^[0-9]*$')], verbose_name='Contact 10 digit Phone Number')),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries_plus.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-modified'],
            },
        ),
    ]
