# Generated by Django 3.1.10 on 2021-05-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210508_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accept_cookies',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Not compulsary, But good practive to differentciate owners', max_length=255, null=True, verbose_name='Middle Name'),
        ),
    ]
