# Generated by Django 3.1.10 on 2021-05-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210509_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_deposited',
            field=models.BooleanField(default=False),
        ),
    ]
