# Generated by Django 3.1.10 on 2021-05-10 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210510_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userverify',
            options={'ordering': ['-modified'], 'verbose_name': 'User Verify', 'verbose_name_plural': 'User Verifies'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userverify',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userverify', to=settings.AUTH_USER_MODEL),
        ),
    ]
