# Generated by Django 3.1.10 on 2021-05-10 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210510_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
