# Generated by Django 3.1.10 on 2021-05-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210510_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
