# Generated by Django 3.1.10 on 2021-05-10 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210510_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deposit_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='member_since',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
