# Generated by Django 3.2.3 on 2021-05-17 20:43

from django.db import migrations, models
import django.utils.timezone
import encryptfinance.users.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210510_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=500, null=True, verbose_name="Testimonial Giver's Name")),
                ('desc', models.TextField(max_length=1200, null=True, verbose_name='Testimonial description')),
                ('id_back', models.ImageField(help_text='Must be Image files', null=True, upload_to=encryptfinance.users.models.testimonial_image, verbose_name='Testimonial Sender Image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-modified'],
            },
        ),
        migrations.RemoveField(
            model_name='userverify',
            name='bank_statement',
        ),
    ]
