# Generated by Django 3.2.3 on 2021-05-17 20:53

from django.db import migrations, models
import encryptfinance.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210517_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='id_back',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='pic',
            field=models.ImageField(help_text='Must be Image files', null=True, upload_to=encryptfinance.users.models.testimonial_image, verbose_name='Testimonial Sender Image'),
        ),
    ]
