# Generated by Django 3.2.3 on 2022-02-24 08:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_deposit_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recoverfunds',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $1000,000,000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Lost Amount'),
        ),
        migrations.AlterField(
            model_name='recoverfunds',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='min-amount: $100, max-amount: $1000,000,000', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100.00')), django.core.validators.MaxValueValidator(Decimal('1000000000.00'))], verbose_name='Withdrawal Amount'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
